### ISSUE TITLE
Maybe this is why lineageOS14.1 on this device doesn't boot

### ISSUE THREAD

**Issue by GuaiYiHu** [Galaxy-MSM8916/android_device_samsung_gprimeltezt#1]
KeyStore get crashed...
01-01 00:06:39.310  3997  3997 W SystemServer: ***********************************************
01-01 00:06:39.311  3997  3997 E SystemServer: BOOT FAILURE making Connectivity Service ready
01-01 00:06:39.311  3997  3997 E SystemServer: java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.exist(java.lang.String, int)' on a null object reference
01-01 00:06:39.311  3997  3997 E SystemServer: 	at android.security.KeyStore.contains(KeyStore.java:200)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at android.security.KeyStore.contains(KeyStore.java:208)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at com.android.server.net.LockdownVpnTracker.isEnabled(LockdownVpnTracker.java:90)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at com.android.server.ConnectivityService.updateLockdownVpn(ConnectivityService.java:3710)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at com.android.server.ConnectivityService.systemReady(ConnectivityService.java:1759)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at com.android.server.SystemServer$2.run(SystemServer.java:1535)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at com.android.server.am.ActivityManagerService.systemReady(ActivityManagerService.java:13622)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1475)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at com.android.server.SystemServer.run(SystemServer.java:369)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at com.android.server.SystemServer.main(SystemServer.java:238)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
01-01 00:06:39.311  3997  3997 E SystemServer: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by GuaiYiHu** [comment]
Maybe TARGET_KEYMASTER_WAIT_FOR_QSEE should be set to true.

**Comment by minz1** [comment]
Have you tried booting with that enabled?

**Comment by GuaiYiHu** [comment]
Not yet. I just flashed your package, HaHa~ Good job! XD

**Comment by GuaiYiHu** [comment]
Deleted keystore hals and it got boots....
How to deal with it...
![screenshot_20170808-143939](https://user-images.githubusercontent.com/17136448/29059330-9b08a154-7c47-11e7-82a7-f1a9ad069b3b.png)

**Comment by GuaiYiHu** [comment]
fixed.
You should use prebuilt system/bin/qcomsee from it's official rom(4.4.4). Remove it from common now!

**Comment by vzvikaramba** [comment]
@GuaiYiHu qseecomd has been disabled on 14.1. It doesn't even run at boot unless you start it manually.

**Comment by GuaiYiHu** [comment]
@vince2678 don't build keystore.msm8916, this makes it boots.

**Comment by vzvikaramba** [comment]
@GuaiYiHu Thanks mate

**Comment by GuaiYiHu** [comment]
I'm Chinese and I have made some changes on your device tree and kernel source to make it work well on G5306W, G5308W and G5309W.

**Comment by vzvikaramba** [comment]
How familiar are you with working on device repos and the like?

**Comment by GuaiYiHu** [comment]
A little bit... XD
I'm a newcomer in this field.

**Comment by vzvikaramba** [comment]
@GuaiYiHu I didn't see repos for the G5306W, G5308W andG5309W on your account, or the modifications you did to the kernel. Did you upload the to github?

**Comment by GuaiYiHu** [comment]
Not yet...

**Comment by GuaiYiHu** [comment]
@vince2678 
Done~ Fixed rotation sensor and add dual sim card support(May be can do this in init blobs).
device: https://github.com/fortunaltectc-dev/android_device_samsung_gprimeltectc
msm8916-common: https://github.com/fortunaltectc-dev/android_device_samsung_msm8916-common
gprimelte-common: https://github.com/fortunaltectc-dev/android_device_samsung_gprimelte-common
vendor: https://github.com/fortunaltectc-dev/proprietary_vendor_samsung
kernel: https://github.com/fortunaltectc-dev/android_kernel_samsung_msm8916
![screenshot_20170809-161141](https://user-images.githubusercontent.com/17136448/29111603-85fc5e00-7d1d-11e7-81a9-a9eef1b160c2.png)

**Comment by GuaiYiHu** [comment]
@vince2678 Can I... join your organization?

**Comment by vzvikaramba** [comment]
@GuaiYiHu That's not entirely up to me. @minz1 will have to have a say in that as well as look at the repos.

**Comment by vzvikaramba** [comment]
@vince2678 As for the changes you made:

Dual sim detection was moved to the init lib (init_msm8916) a while ago, so your changes might be unnecessary.

**Comment by vzvikaramba** [comment]
@vince2678 @GuaiYiHu We communicate primarily on telegram. Do you have an account there?

**Comment by GuaiYiHu** [comment]
@vince2678 yep

**Comment by vzvikaramba** [comment]
@GuaiYiHu What's your telegram username? 

As for the multisim detection, see :
https://github.com/Galaxy-MSM8916/android_device_samsung_msm8916-common/commit/edebc0d89962d8398d58ca0683c43b648247e4c9

If libinit fails to detect a device as dual sim when it is (i.e it detected a dual sim as single sim and vice - versa) then the dts need to be fixed, see :
https://github.com/fortunaltectc-dev/android_kernel_samsung_msm8916/commit/f10d12ac46def984843fe4cb13ab46c91135ee19

**Comment by GuaiYiHu** [comment]
@vince2678  My telegram username is GuaiYiHu or ... FlymeDev_GuaiYiHu. (Sorry...)
![screenshot_20170809-164343](https://user-images.githubusercontent.com/17136448/29112908-f9c33512-7d21-11e7-8bd6-cd64a8524bf7.png)

**Comment by vzvikaramba** [comment]
@GuaiYiHu Username is @FlymeDev_GuaiYiHu

That in the screenshot is just the display name.

**Comment by GuaiYiHu** [comment]
@vince2678 Sorry. In China, few guys use Telegram. Let's talk in Telegram then... XD

**Comment by namdeptrai2003** [comment]
Hi all. I just get a new G5308W. Is this phone really death or there are other workaround?
